Tilbake.MVC/Models/AllRiskViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;

namespace Tilbake.MVC.Models
{
    public class AllRiskViewModel
    {
        public Guid Id { get; set; }
        public Guid QuoteItemId { get; set; }
        public Guid QuoteId { get; set; }
        public Guid PolicyRiskId { get; set; }

        [Display(Name = "Description")]
        public Guid RiskItemId { get; set; }

        public string RiskItem { get; set; }

        public Guid ModifiedBy { get; set; }

        //  SelectLists
        public SelectList RiskItemList { get; set; }
    }
}

Tilbake.MVC/Models/CustomerCarrierViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tilbake.MVC.Models
{
    public class CustomerCarrierViewModel
    {
        public Guid CustomerId { get; set; }
        public Guid CarrierId { get; set; }

        [Display(Name = "Carriers")]
        public List<Guid>? CarrierIds { get; set; } = new();

        public virtual CarrierViewModel? Carrier { get; set; }

        public MultiSelectList? CarrierList { get; set; }
    }
}

Tilbake.MVC/Models/FileTemplateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Tilbake.Core.Enums;
using Tilbake.Core.Models;

namespace Tilbake.MVC.Models
{
    public class FileTemplateViewModel : BaseViewModel
    {
        public Guid PortfolioId { get; set; }

        [Display(Name = "File Type")]
        public FileType FileType { get; set; }

        [Display(Name = "Delimiter")]
        public string? Delimiter { get; set; }

        public List<FileTemplateRecord> FileTemplateRecords { get; } = new();

        //  Descriptions
        public string? PortfolioName { get; set; }

        //  SelectLists
        public SelectList? FileTypeList { get; set; }
    }
}

Tilbake.MVC/Models/InvoiceItemViewModel.cs
using System;
using Tilbake.Core.Models;

namespace Tilbake.MVC.Models
{
    public class InvoiceItemViewModel
    {
        public Guid Id { get; set; }
        public Guid InvoiceId { get; set; }
        public Guid PolicyRiskId { get; set; }

        public PolicyRisk PolicyRisk { get; set; }
    }
}

Tilbake.MVC/Models/QuoteItemViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;
using Tilbake.Core.Models;

namespace Tilbake.MVC.Models
{
    public class QuoteItemViewModel
    {
        public Guid CustomerRiskId { get; set; }
        public Guid Id { get; set; }
        public Guid QuoteId { get; set; }

        [Display(Name = "Cover Type")]
        public Guid CoverTypeId { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Sum Insured")]
        public decimal SumInsured { get; set; }

        [Display(Name = "Premium")]
        public decimal Premium { get; set; }

        [Display(Name = "Excess")]
        public string Excess { get; set; }

        public CoverType CoverType { get; set; }
        public Quote Quote { get; set; }

        //  SelectLists
        public SelectList CoverTypeList { get; set; }
    }
}

Tilbake.MVC/Controllers/CustomersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tilbake.Core;
using Tilbake.Core.Models;
using Tilbake.MVC.Areas.Identity;
using Tilbake.MVC.Helpers;
using Tilbake.MVC.Models;

namespace Tilbake.MVC.Controllers
{
    public class CustomersController : BaseController
    {
        public CustomersController(
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<ApplicationUser> userManager) : base(unitOfWork, mapper, userManager)
        {

        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            var result = await _unitOfWork.Customers.GetAll(r => r.OrderBy(n => n.LastName));
            var model = _mapper.Map<IEnumerable<Customer>, IEnumerable<CustomerViewModel>>(result);
            return View(model);
        }

        public async Task<IActionResult> Search(string searchString = "~#")
        {
            var result = await _unitOfWork.Customers.GetAll(r => r.OrderBy(n => n.LastName));
            var customerModel = _mapper.Map<IEnumerable<Customer>, IEnumerable<CustomerViewModel>>(result);

            if (!String.IsNullOrEmpty(searchString))
            {
                customerModel = customerModel.Where(r => r.LastName.Contains(searchString, StringComparison.CurrentCultureIgnoreCase)
                                        || r.FirstName.Contains(searchString, StringComparison.CurrentCultureIgnoreCase)
                                        || r.IdNumber.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
            }

            CustomerSearchViewModel model = new()
            {
                SearchString = "",
                CustomerViewModels = customerModel
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetByIdNumber(string idNumber)
        {
            var result = await _unitOfWork.Customers.GetByIdNumber(idNumber);
            if(result != null)
            {
                var model = _mapper.Map<Customer, CustomerViewModel>(result);
                return Json(new { model.Id, model.FirstName, model.LastName, model.IdNumber, model.CustomerNumber });
            }

            return Json(result);
        }

        // GET: Customers/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var result = await _unitOfWork.Customers.GetById(id);            
            if (result == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<Customer, CustomerViewModel>(result);
            return View(model);
        }

        // GET: Customers/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var result = await _unitOfWork.Customers.GetById(id);
            if (result == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<Customer, CustomerViewModel>(result);

            //var cityId = model.Address.CityId;
            //var city = await _unitOfWork.Cities.GetById(cityId);
            //var countryId = city.CountryId;

            var carriers = await _unitOfWork.Carriers.GetAll(r => r.OrderBy(n => n.Name));
            //var cities = await _unitOfWork.Cities.GetByCountryId(countryId);
            var customerTypes = await _unitOfWork.CustomerTypes.GetAll(r => r.OrderBy(n => n.Name));
            var customerStatuses = await _unitOfWork.CustomerStatuses.GetAll(r => r.OrderBy(n => n.Name));
            var countries = await _unitOfWork.Countries.GetAll(r => r.OrderBy(n => n.Name));
            var genders = await _unitOfWork.Genders.GetAll(r => r.OrderBy(n => n.Name));
            var idDocumentTypes = await _unitOfWork.IdDocumentTypes.GetAll(r => r.OrderBy(n => n.Name));
            var maritalStatuses = await _unitOfWork.MaritalStatuses.GetAll(r => r.OrderBy(n => n.Name));
            var occupations = await _unitOfWork.Occupations.GetAll(r => r.OrderBy(n => n.Name));
            var titles = await _unitOfWork.Titles.GetAll(r => r.OrderBy(n => n.Name));

            model.CountryList = MVCHelperExtensions.ToSelectList(countries, model.CountryId);
            model.CustomerTypeList = MVCHelperExtensions.ToSelectList(customerTypes, model.CustomerTypeId);
            model.CountryList = MVCHelperExtensions.ToSelectList(countries, model.CountryId);
            model.GenderList = MVCHelperExtensions.ToSelectList(genders, model.GenderId);
            model.IdDocumentTypeList = MVCHelperExtensions.ToSelectList(idDocumentTypes, model.IdDocumentTypeId);
            model.MaritalStatusList = MVCHelperExtensions.ToSelectList(maritalStatuses, model.MaritalStatusId);
            model.OccupationList = MVCHelperExtensions.ToSelectList(occupations, model.OccupationId);
            model.TitleList = MVCHelperExtensions.ToSelectList(titles, model.TitleId);

            model.CarrierList = MVCHelperExtensions.ToMultiSelectList(carriers, model.CarrierIds);

            //model.AddressCountryList = MVCHelperExtensions.ToSelectList(countries, countryId);
            //model.CityList = MVCHelperExtensions.ToSelectList(cities, cityId);
            return View(model);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var customer = _mapper.Map<CustomerViewModel, Customer>(model);
                _unitOfWork.Customers.Update(model.Id, customer);

                var customerId = customer.Id;
                var customerCarriers = await _unitOfWork.CustomerCarriers.Get(r => r.CustomerId == customerId);

                if (customerCarriers != null)
                {
                    _unitOfWork.CustomerCarriers.DeleteRange(customerCarriers);
                }

                var newCustomerCarriers = new List<CustomerCarrier>();

                foreach (var item in model.CarrierIds)
                {
                    CustomerCarrier customerCarrier = new()
                    {
                        CustomerId = customerId,
                        CarrierId = item
                    };
                    newCustomerCarriers.Add(customerCarrier);
                }
                _unitOfWork.CustomerCarriers.AddRange(newCustomerCarriers);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }

            var carriers = await _unitOfWork.Carriers.GetAll(r => r.OrderBy(n => n.Name));
            var cities = await _unitOfWork.Cities.GetByCountryId(model.CountryId);
            var customerTypes = await _unitOfWork.CustomerTypes.GetAll(r => r.OrderBy(n => n.Name));
            var customerStatuses = await _unitOfWork.CustomerStatuses.GetAll(r => r.OrderBy(n => n.Name));
            var countries = await _unitOfWork.Countries.GetAll(r => r.OrderBy(n => n.Name));
            var genders = await _unitOfWork.Genders.GetAll(r => r.OrderBy(n => n.Name));
            var idDocumentTypes = await _unitOfWork.IdDocumentTypes.GetAll(r => r.OrderBy(n => n.Name));
            var maritalStatuses = await _unitOfWork.MaritalStatuses.GetAll(r => r.OrderBy(n => n.Name));
            var occupations = await _unitOfWork.Occupations.GetAll(r => r.OrderBy(n => n.Name));
            var titles = await _unitOfWork.Titles.GetAll(r => r.OrderBy(n => n.Name));

            model.CountryList = MVCHelperExtensions.ToSelectList(countries, model.CountryId);
            model.CustomerTypeList = MVCHelperExtensions.ToSelectList(customerTypes, model.CustomerTypeId);
            model.CountryList = MVCHelperExtensions.ToSelectList(countries, model.CountryId);
            model.GenderList = MVCHelperExtensions.ToSelectList(genders, model.GenderId);
            model.IdDocumentTypeList = MVCHelperExtensions.ToSelectList(idDocumentTypes, model.IdDocumentTypeId);
            model.MaritalStatusList = MVCHelperExtensions.ToSelectList(maritalStatuses, model.MaritalStatusId);
            model.OccupationList = MVCHelperExtensions.ToSelectList(occupations, model.OccupationId);
            model.TitleList = MVCHelperExtensions.ToSelectList(titles, model.TitleId);

            model.CarrierList = MVCHelperExtensions.ToMultiSelectList(carriers, model.CarrierIds);

            //model.Address.CountryList = MVCHelperExtensions.ToSelectList(countries, model.Address.CountryId);
            //model.Address.CityList = MVCHelperExtensions.ToSelectList(cities, model.Address.CityId);

            return View(model);
        }
    }
}

Tilbake.MVC/Controllers/InvoicesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tilbake.Core;
using Tilbake.Core.Models;
using Tilbake.MVC.Areas.Identity;
using Tilbake.MVC.Helpers;
using Tilbake.MVC.Models;

namespace Tilbake.MVC.Controllers
{
    public class InvoicesController : BaseController
    {
        public InvoicesController(
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<ApplicationUser> userManager) : base(unitOfWork, mapper, userManager)
        {

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _unitOfWork.Invoices.GetAll(r => r.OrderBy(n => n.InvoiceNumber));
            var model = _mapper.Map<IEnumerable<Invoice>, IEnumerable<InvoiceViewModel>>(result);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid policyId)
        {
            var policyRisks = await _unitOfWork.PolicyRisks.GetByPolicyId(policyId);
            
            var invoiceStatuses = await _unitOfWork.InvoiceStatuses.GetAll();
            var taxes = await _unitOfWork.Taxes.GetAll();

            InvoiceViewModel model = new()
            {
                PolicyId = policyId,
                Amount = policyRisks.Sum(r => r.Premium),
                InvoiceStatusList = MVCHelperExtensions.ToSelectList(invoiceStatuses, Guid.Empty)
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(InvoiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var policyId = model.PolicyId;
                var policyRisks = await _unitOfWork.PolicyRisks.Get(r => r.PolicyId == policyId);

                var invoice = _mapper.Map<InvoiceViewModel, Invoice>(model);

                var taxes = await _unitOfWork.Taxes.GetAll(r => r.OrderByDescending(n => n.TaxDate));
                var taxRate = taxes.Take(1).Select(r => r.TaxRate).FirstOrDefault();

                invoice.Id = Guid.NewGuid();
                invoice.Amount = policyRisks.Sum(r => r.Premium);
                //invoice.TaxRate = taxRate;
                invoice.TaxAmount = invoice.Amount * taxRate / 100;
                invoice.ReducingBalance = invoice.Amount;
                invoice.DateAdded = DateTime.Now;
                await _unitOfWork.Invoices.AddAsync(invoice);

                var invoiceId = invoice.Id;

                List<InvoiceItem> invoiceItems = new();
                foreach (var item in policyRisks)
                {
                    InvoiceItem invoiceItem = new()
                    {
                        Id = Guid.NewGuid(),
                        InvoiceId = invoiceId,
                        PolicyRiskId = item.Id
                    };
                    invoiceItems.Add(invoiceItem);
                }
                _unitOfWork.InvoiceItems.AddRange(invoiceItems);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction("Details", "Policies", new { id = model.PolicyId });
            }

            var invoiceStatuses = await _unitOfWork.InvoiceStatuses.GetAll();
            model.InvoiceStatusList = MVCHelperExtensions.ToSelectList(invoiceStatuses, model.InvoiceStatusId);
            return View(model);
        }

        // GET: Invoices/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _unitOfWork.Invoices.GetById(id);
            if (result == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<Invoice, InvoiceViewModel>(result);
            return View(model);
        }

        public IActionResult Invoice()
        {
            return View();
        }
    }
}

Tilbake.MVC/Controllers/PoliciesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Tilbake.Core;
using Tilbake.Core.Models;
using Tilbake.MVC.Areas.Identity;
using Tilbake.MVC.Models;

namespace Tilbake.MVC.Controllers
{
    [Authorize]
    public class PoliciesController : BaseController
    {
        public PoliciesController(
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<ApplicationUser> userManager) : base(unitOfWork, mapper, userManager)
        {

        }

        public async Task<IActionResult> Index(Guid portfolioCustomerId)
        {
            var result = await _unitOfWork.Policies.GetByPorfolioCustomerId(portfolioCustomerId);
            var model = _mapper.Map<IEnumerable<Policy>, IEnumerable<PolicyViewModel>>(result);
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _unitOfWork.Policies.GetById(id);
            if (result == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<Policy, PolicyViewModel>(result);
            return View(model);
        }
    }
}

Tilbake.MVC/Views/Shared/_BankBranches.cshtml
@model IEnumerable<BankBranchViewModel>

@{ 
    var bankid = ViewBag.BankId;
}

<div class="card">
    <div class="card-body">
        <div class="d-md-flex justify-content-md-end">
            <div class="form-group">
                <a asp-controller="BankBranches" asp-action="Create" asp-route-bankId="@bankid">New Branch</i></a>
            </div>
        </div>        
        @if (Model.Any())
        {
            <div class="form-group">
                <table id="tblBankBranches" class="table">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Sort Code
                            </th>
                            <th>
                                Swift Code
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a asp-controller="BankBranches" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                                </td>
                                <td>
                                    @item.SortCode
                                </td>
                               <td>
                                    @item.SwiftCode
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <p>No Records Found</p>

        }
    </div>
</div>

Tilbake.MVC/Views/Shared/_CreateAddress.cshtml
@model AddressViewModel

<div class="row">
    <div class="col-12">
        <div class="form-floating">
            <input asp-for="PhysicalAddress" id="PhysicalAddress" class="form-control" />
            <label asp-for="PhysicalAddress" class="control-label"></label>
            <span asp-validation-for="PhysicalAddress" class="text-danger"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-4">
        <div class="form-floating">
            <input asp-for="PostalAddress" class="form-control" />
            <label asp-for="PostalAddress" class="control-label"></label>
            <span asp-validation-for="PostalAddress" class="text-danger"></span>
        </div>
    </div>
    <div class="col-4">
        <div class="form-floating">
            <select asp-for="CountryId" id="AddressCountryId" class ="form-select" asp-items="@Model.CountryList"></select>
            <label asp-for="CountryId" class="control-label"></label>
        </div>
    </div>
    <div class="col-4">
        <div class="form-floating">
            <select asp-for="CityId" id="AddressCityId" class="form-select" asp-items="@Model.CityList"></select>
            <label asp-for="CityId" class="control-label"></label>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // Do something here
    });

    function FillCountry() {
        $.ajax({
            url: '@(Url.Action("GetCountries", "Countries"))',
            traditional: true,
            dataType: 'json',
            type: 'GET',
            error: function () {
                alert("An error occurred.");
            },
            success: function (countries) {
                $('#AddressCountryId').empty();   // clear before appending new list
                $.each(countries, function (index, country) {
                    $('#AddressCountryId').append($('<option></option>').val(country.id).html(country.name));
                });
            }
        });
    }

</script>

Tilbake.MVC/Views/Shared/_CustomerCarriers.cshtml
@model IEnumerable<CustomerCarrierViewModel>

<div class="card text-center">
    <div class="card-body">
        <h6 class="card-title mb-0">Carriers</h6>
    </div>
    @if(Model.Any())
    {
        <div class="row mb-3 justify-content-md-center">
            <div class="col-md-auto">
                @foreach(var item in Model)
                {
                    <span class="badge rounded-pill bg-primary px-3">@item.Carrier.Name</span>
                }
            </div>
        </div>

    } else {
        <span class="card-text text-muted mb-0"><small>No Carriers</small></span>
    }
</div>

Tilbake.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tilbake</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Tilbake.MVC.styles.css" asp-append-version="true" />

    <!-- Bootstrap 5.1.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css">

    <!-- Line Awesome Icons -->
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">

    <!-- Formvalidation -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.2-dev/css/formValidation.min.css" integrity="sha512-B9GRVQaYJ7aMZO3WC2UvS9xds1D+gWQoNiXiZYRlqIVszL073pHXi0pxWxVycBk0fnacKIE3UHuWfSeETDCe7w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/2ab1015e74.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tilbake</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarAccounting" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Accounting
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarAccounting">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Record Payment</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Portfolios" asp-action="Index">Portfolios</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="UserPortfolios" asp-action="Index">Assign Portfolios</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customers" asp-action="Search">Customers</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="CommissionRates" asp-action="Index">Commission Rates</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="RatingTables" asp-action="Index">Rating Tables</a>                                    
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Claims">Claims</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Banks" asp-action="Index">Banks</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Carriers" asp-action="Index">Carriers</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Insurers" asp-action="Index">Insurers</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Occupations" asp-action="Index">Occupations</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tilbake - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.min.js"></script>

    <!-- Bootstrap 5.1.3 Javascript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
    <!-- Formvalidation -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.2-dev/js/formValidation.min.js" integrity="sha512-DlXWqMPKer3hZZMFub5hMTfj9aMQTNDrf0P21WESBefJSwvJguz97HB007VuOEecCApSMf5SY7A7LkQwfGyVfg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>